#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "owncloud"
name = "ownCloud"
description.en = "Online storage, file sharing platform"
description.fr = "Stockage en ligne, plateforme de partage de fichiers"

version = "8.0.1~ynh2"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
website = "https://owncloud.com"
demo = "https://ocis.owncloud.com"
admindoc = "https://doc.owncloud.com/ocis/next/"
code = "https://github.com/owncloud/ocis"
cpe = "cpe:2.3:a:owncloud:owncloud"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = true

disk = "100M"
ram.build = "800M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["cs", "de", "en", "es", "fr", "gl", "it"]
    default = "fr"

    [install.password]
    type = "password"

[resources]

    [resources.sources.main]
    amd64.url = "https://github.com/owncloud/ocis/releases/download/v8.0.1/ocis-8.0.1-linux-amd64"
    amd64.sha256 = "43bd91402768ade4bb0937eb06b1b231600f621506d1ebb7597d6c532ba55de6"
    arm64.url = "https://github.com/owncloud/ocis/releases/download/v8.0.1/ocis-8.0.1-linux-arm64"
    arm64.sha256 = "12767ba28ae5c2fd152d3a229f2d0fa8bab173d551ba970e729d51591539fcfc"
    armhf.url = "https://github.com/owncloud/ocis/releases/download/v8.0.1/ocis-8.0.1-linux-arm"
    armhf.sha256 = "b5a14d8b503adecad8e5de8b6fbf5ab3e5652dd454f7d9361c844537e80681ed"
    i386.url = "https://github.com/owncloud/ocis/releases/download/v8.0.1/ocis-8.0.1-linux-386"
    i386.sha256 = "02680a6ab06b6376e92401123e2f6cc0ddceaa81f75d7cf38588b97b94e43203"
    in_subdir = false
    rename = "ocis"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^ocis-.*-linux-amd64$"
    autoupdate.asset.arm64 = "^ocis-.*-linux-arm64$"
    autoupdate.asset.armhf = "^ocis-.*-linux-arm$"
    autoupdate.asset.i386 = "^ocis-.*-linux-386$"

    [resources.system_user]
    allow_email = true
    
    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["config"]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false
    api.url = "/ocs"
    api.auth_header = false
    api.show_tile = false
    api.protected= true
    api.allowed = ["visitors"]

    [resources.ports]
